### ISSUE TITLE
User Profile : Dropdown box arrows inconsistency

### ISSUE THREAD

**Issue by Blandine-AA** [hhaccessibility/hhaccessibility.github.io#315]
In the home section, the dropdown box styles are not the same. 
- [x] The arrows are different. They should be aligned and of the same size.
- [x] Also check that the font size is the same for the field names.
![image](https://cloud.githubusercontent.com/assets/20052162/25433809/be7aafac-2a57-11e7-8220-244e5b0296fd.png)

**Comment by joshi1983** [comment]
The easiest fix for this seems to be hiding the data list arrow completely.  This may help anyone working on removing the arrow: http://stackoverflow.com/questions/20937475/remove-datalist-dropdown-arrow-in-chrome

Note that the two elements have a different meaning which is probably why web browsers show the arrows differently.  It visually conveys that the country selector requires one of its options to be selected while the state/province element there merely suggests its options.

**Comment by Blandine-AA** [comment]
This can be fixed en release 0.0.4 as scheduled

**Comment by joshi1983** [comment]
I mentioned to @Manasab7 that we probably want CSS to control how the arrows look.  This might fight with how various browsers make them look by default.  In the end, the best solution will be tested and look consistent in multiple browsers.  They might look different in each browser but most important would be to make the arrow look the same in Province and country.

**Comment by joshi1983** [comment]
I merged Mana's changes with some tweaks.

In Chrome with my laptop the arrows look like this now:
![image](https://user-images.githubusercontent.com/11838191/36290539-c7413c1c-1293-11e8-94f6-f0c8702b97cd.png)

@Manasab7 can you test with your browser and phone too?  The changes were deployed to app.accesslocator.com.

@Manasab7 if you're curious about the specific tweaks I made, they're all in this commit: https://github.com/hhaccessibility/hhaccessibility.github.io/pull/508/commits/fe4853eaafa3eaf6a4b6462c1e59da0f8462d7f7

**Comment by Manasab7** [comment]
Verified the changes in Safari (v11.2.5) on iPhone, Mozilla Firefox (v58.0.1)  and noticed that State/Province field dropdown arrow is not visible. However, Country field dropdown looks fine in all browsers(mobile browsers as well). Font size is the same for all field names.

**Comment by Blandine-AA** [comment]
I this in this case the same type of dropdown box should be used for Country as well as for Province/State. The behavior is still not intuitive... But good enough! 

I will set this as a P4 for now and we will review it toward the end of the release if we have time to fix in 0.0.5.  Otherwise I will move it to 0.0.6.

**Comment by Blandine-AA** [comment]
Moving this to 0.0.7 as a workaround is implement in #523

**Comment by joshi1983** [comment]
@passionInfinite 's work to replace with a select in #523 was deployed which looks like it should fix this issue too.  I'm marking this ready for testing so Blandine can review and potentially close.

**Comment by singlaneha2205** [comment]
@joshi1983 and @Blandine-AA I tested the issue the arrows issue. It is working as expected on IE, Edge, Chrome, Firefox. Refer to the screenshots below.
Edge: 
![image](https://user-images.githubusercontent.com/40703592/42404598-9f4b11a4-8158-11e8-9023-2d89e3d2fd64.png)
Firefox: 
![image](https://user-images.githubusercontent.com/40703592/42404606-b9affc8a-8158-11e8-8b78-f0910457c1cb.png)
Chrome:
![image](https://user-images.githubusercontent.com/40703592/42404612-cabb1a5a-8158-11e8-807e-c9bf656f2393.png)
IE:
![image](https://user-images.githubusercontent.com/40703592/42404626-e0668556-8158-11e8-88fc-e9c087e6a2e4.png)
 So I am marking it Tested Successfully

**Comment by joshi1983** [comment]
I agree that every arrow looks very consistent in your screenshot so I'm closing.
