### ISSUE TITLE
The Save Profile button remains disabled when try to update the accessibility requirements.

### ISSUE THREAD

**Issue by singlaneha2205** [hhaccessibility/hhaccessibility.github.io#607]
The save profile button remains disabled when we try to update only the accessibility requirements. But if we update ant other fields along with the accessibility requirements the button is enabled. right now we are not able to update the accessibility requirements solely. 
[Save Profile Issue.docx](https://github.com/hhaccessibility/hhaccessibility.github.io/files/2164264/Save.Profile.Issue.docx)

**Comment by joshi1983** [comment]
@singlaneha2205 can you also reproduce that on https://app.accesslocator.com ?  I see the "Save Profile" button enabled when I do it.

For now, Hardik is working on a problem where demo.accesslocator.com is identical to app.accesslocator.com but you might have tested when demo.accesslocator.com represented a May 20 version.

**Comment by singlaneha2205** [comment]
@joshi1983 I checked the issue on https://app.accesslocator.com. The Save Profile button gets enabled when we select or deselect the checkboxes. The actual issue is with the Select All button present in each accessibility requirements. If the user updates the accessibility requirements using Select All or Unselect All button the Save Profile button remains disabled.

**Comment by joshi1983** [comment]
@singlaneha2205 thanks.  I was able to reproduce the problem with that.

Here is a screenshot showing the 2 buttons related to this bug in case it helps anyone else trying to reproduce the problem.
![image](https://user-images.githubusercontent.com/11838191/42336543-018ea130-8052-11e8-974f-82e66a0fffce.png)

**Comment by M4ttoF** [comment]
Fixed with #617 
Needs Testing

**Comment by singlaneha2205** [comment]
I tested the issue. Seems like Issue is not resolved yet. As when i Try to edit the fields using Select All and Unselect All button the Save profile button remains disabled

**Comment by joshi1983** [comment]
This was mislabeled as ready yesterday as there was some confusion around the testing process but that should be resolved now.

It can be tested on https://app.accesslocator.com now.  The suggested minimum steps for testing are:
1. Sign in to the profile.
1. Click "Select all"
1. Verify that the Save Profile button is enabled.
1. Click "Unselect all"
1. Verify that the Save Profile button is disabled.  Going back to the original values should disable the button because there is nothing to save.
1. Adjust the location search radius.
1. Verify the Save Profile button is enabled.
1. Adjust it back to the original value.
1. Verify that the Save Profile button is disabled.  Again, back to original values means there is nothing to save

The "Leave" dialog bug from another issue should also be fixed now so that it shows exactly when navigating away from the profile when "Save Profile" is enabled.

**Comment by singlaneha2205** [comment]
@joshi1983 I tried the above steps on  https://app.accesslocator.com but the behavior is not as expected. The Save Profile button is not enabled when we use select All or increase the location search radius.
So I am marking it as Failed Testing.

**Comment by M4ttoF** [comment]
@singlaneha2205 did you refresh your cache first with Ctrl+Shift+R?
I just tested both and they work fine for me

**Comment by singlaneha2205** [comment]
@M4ttoF Thank you. I tested it after clearing the cache and it worked as expected. @joshi1983 we can go ahead and close this issue.

**Comment by joshi1983** [comment]
I'm closing as @singlaneha2205 tested it too.
